---
Name: socialmeta
---
SilverStripe\CMS\Model\SiteTree:
  extensions:
    - Innoweb\SocialMeta\Extensions\SiteTreeExtension

SilverStripe\Security\Member:
  extensions:
    - Innoweb\SocialMeta\Extensions\AuthorExtension

Page:
  socialmeta_opengraph_type: 'article'
  
Innoweb\SocialMeta\Extensions\SiteTreeExtension:
  image_size_twitter:
    width: 1024
    height: 512
  image_size_opengraph:
    width: 1200
    height: 628

---
Only:
  moduleexists: 'symbiote/silverstripe-multisites'
---
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - Innoweb\SocialMeta\Extensions\MultisiteCurrentConfigSiteConfigExtension
Symbiote\Multisites\Model\Site:
  extensions:
    - Innoweb\SocialMeta\Extensions\ConfigExtension
    - Innoweb\SocialMeta\Extensions\MultisiteSiteExtension

---
Except:
  moduleexists: 'symbiote/silverstripe-multisites'
---
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - Innoweb\SocialMeta\Extensions\CurrentConfigSiteConfigExtension
    - Innoweb\SocialMeta\Extensions\ConfigExtension
