---
Name: socialmetadata
---
SilverStripe\CMS\Model\SiteTree:
  extensions:
    - Innoweb\SocialMeta\Extensions\SiteTreeExtension
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - Innoweb\SocialMeta\Extensions\ConfigExtension
SilverStripe\Security\Member:
  extensions:
    - Innoweb\SocialMeta\Extensions\AuthorExtension
Innoweb\SocialMeta\Extensions\SiteTreeExtension:
  facebook_page_type:
    Page: 'article'
Innoweb\SocialMeta\Extensions\ConfigExtension:
  multisites_enable_global_settings: false
SilverStripe\Forms\FormField:
  extensions:
    - Innoweb\SocialMeta\Forms\FormFieldAttributesExtension
---
Only:
  classexists: 'Symbiote\Multisites\Multisites'
---
Symbiote\Multisites\Model\Site:
  extensions:
    - Innoweb\SocialMeta\Extensions\ConfigExtension
